server:
  port: 8011
spring:
  cache:
    type: redis
  data:
    redis:
      # 可配置参数：https://www.bbsmax.com/A/x9J2RXbMJ6/
      #地址
      host: 127.0.0.1
      #端口号
      port: 6379
      database: 0
      #如果有密码，请填写
      password:
      #连接超时时间
      timeout: 3000
      #最大空闲连接数
      maxIdle: 200
      #最大连接数(空闲+等待)
      maxTotal: 500
      #最大建立连接等待时间。
      maxWaitMillis: PT3S
      #连接多久没有使用设置为闲置,检测线程直接剔除闲置
      minEvictableIdleTimeMillis: PT300S

      #每次释放连接的最大数目,默认3
      numTestsPerEvictionRun: 1024
      #   后台检测线程周期 逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
      timeBetweenEvictionRunsMillis: PT30S
      #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      testOnBorrow: true
      #后台线程对idle连接进行扫描,检测是否有效
      testWhileIdle: true





