server:
  port: 8081
spring:
  application:
    name: elasticJob

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/demo?useUnicode=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456


elasticjob:
  regCenter:
    serverLists: localhost:2181
    namespace: elasticjob-springboot

